### ISSUE TITLE
Add debian packaging files

### ISSUE THREAD

**Issue by szepeviktor** [maxmind/mod_maxminddb#52] opened 2017-11-18 17:44 UTC
It would be nice to run dpkg-buildpackage only to get a .deb file.

Copying https://anonscm.debian.org/cgit/collab-maint/libapache2-mod-bw.git/tree/ may seem interesting.

Thanks.

**Comment by oschwald** [comment] 2017-11-20 23:21
Thanks for raising this. For our purposes, I think this is a dupe of #33 as it is unlikely we would do one without doing the other.

**Closed by oschwald** 2017-11-20 23:21 UTC
